### ISSUE TITLE
Timeout listing flavor and volumes

### ISSUE THREAD

**Issue by dhallam** [ggiamarchi/vagrant-openstack-provider#217]
When running `vagrant openstack flavor-list` or `vagrant openstack volume-list` it times out.  The URLs that are being used are correct.  And I can fetch the data using the same URL and headers using wget.  Note: running `vagrant openstack image-list` *does* work.

```
$ vagrant version
Installed Version: 1.7.2
Latest Version: 1.7.2

You're running an up-to-date version of Vagrant!

$ export VAGRANT_OPENSTACK_LOG=debug
$ export RESTCLIENT_LOG=stdout
$ vagrant openstack flavor-list
2015-02-24 19:00 |  INFO | Authenticating on Keystone
2015-02-24 19:00 |  INFO | Authentication on project **** with user ****
2015-02-24 19:00 | DEBUG | request  => method  : POST
2015-02-24 19:00 | DEBUG | request  => url     : http://identity-domain:5000/v2.0/tokens
2015-02-24 19:00 | DEBUG | request  => headers : {"auth":{"tenantName":"****","passwordCredentials":{"username":"****","password":"****"}}}
RestClient.post "http://identity-domain:5000/v2.0/tokens", "{\"auth\":{\"tenantName\":\"****\",\"passwordCredentials\":{\"username\":\"****",\"password\":\"****\"}}}", "Accept"=>"application/json", "Accept-Encoding"=>"gzip, deflate", "Content-Length"=>"136", "Content-Type"=>"application/json", "Open-Timeout"=>"60", "Timeout"=>"30"
# => 200 OK | application/json 15073 bytes
2015-02-24 19:00 | DEBUG | response => code    : 200
2015-02-24 19:00 | DEBUG | response => headers : ****
2015-02-24 19:00 | DEBUG | response => body    : ****
2015-02-24 19:00 |  INFO | Looking for available endpoints...
2015-02-24 19:00 |  INFO | Selecting endpoints matching region 'region'
2015-02-24 19:00 | DEBUG | request  => method  : GET
2015-02-24 19:00 | DEBUG | request  => url     : http://network-region-domain:9696
2015-02-24 19:00 | DEBUG | request  => headers : {"X-Auth-Token"=>"2644343c9bcb467ca67f069ff895fcbe", :accept=>:json}
RestClient.get "http://network-region-domain:9696", "Accept"=>"application/json", "Accept-Encoding"=>"gzip, deflate", "X-Auth-Token"=>"2644343c9bcb467ca67f069ff895fcbe"
# => 200 OK | application/json 156 bytes
2015-02-24 19:00 | DEBUG | response => code    : 200
2015-02-24 19:00 | DEBUG | response => headers : ****
2015-02-24 19:00 | DEBUG | response => body    : {"versions": [{"status": "CURRENT", "id": "v2.0", "links": [{"href": "http://network-region-domain:9696/v2.0", "rel": "self"}]}]}
RestClient.get "http://image-region-domain:9292", "Accept"=>"application/json", "Accept-Encoding"=>"gzip, deflate", "X-Auth-Token"=>"2644343c9bcb467ca67f069ff895fcbe"
# => 300 MultipleChoices | application/json 715 bytes
2015-02-24 19:00 | DEBUG | response => code    : 300
2015-02-24 19:00 | DEBUG | response => headers : ****
2015-02-24 19:00 | DEBUG | response => body    : {"versions": [{"status": "CURRENT", "id": "v2.2", "links": [{"href": "http://image-region-domain:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.1", "links": [{"href": "http://image-region-domain:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.0", "links": [{"href": "http://image-region-domain:9292/v2/", "rel": "self"}]}, {"status": "CURRENT", "id": "v1.1", "links": [{"href": "http://image-region-domain:9292/v1/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v1.0", "links": [{"href": "http://image-region-domain:9292/v1/", "rel": "self"}]}]}
2015-02-24 19:00 |  INFO |  -- compute        : http://compute-region-domain:8774/v2/a4fa95277a4f4d25b2d8f0e2b3eb6244
2015-02-24 19:00 |  INFO |  -- network        : http://network-region-domain:9696/v2.0
2015-02-24 19:00 |  INFO |  -- volumev2       : http://volume-region-domain:8776/v2/a4fa95277a4f4d25b2d8f0e2b3eb6244
2015-02-24 19:00 |  INFO |  -- image          : http://image-region-domain:9292/v2/
2015-02-24 19:00 |  INFO |  -- metering       : http://metering-region-domain:8777
2015-02-24 19:00 |  INFO |  -- cloudformation : http://orchestration-region-domain:8000/v1/
2015-02-24 19:00 |  INFO |  -- volume         : http://volume-region-domain:8776/v1/a4fa95277a4f4d25b2d8f0e2b3eb6244
2015-02-24 19:00 |  INFO |  -- orchestration  : http://orchestration-region-domain:8004/v1/a4fa95277a4f4d25b2d8f0e2b3eb6244
2015-02-24 19:00 |  INFO |  -- identity       : http://identity-domain:5000/v2.0
2015-02-24 19:00 | DEBUG | get_all_flavors - start
2015-02-24 19:00 | DEBUG | request  => method  : GET
2015-02-24 19:00 | DEBUG | request  => url     : http://compute-region-domain:8774/v2/a4fa95277a4f4d25b2d8f0e2b3eb6244/flavors/detail
2015-02-24 19:00 | DEBUG | request  => headers : {"X-Auth-Token"=>"2644343c9bcb467ca67f069ff895fcbe", :accept=>:json}
RestClient.get "http://compute-region-domain:8774/v2/a4fa95277a4f4d25b2d8f0e2b3eb6244/flavors/detail", "Accept"=>"application/json", "Accept-Encoding"=>"gzip, deflate", "X-Auth-Token"=>"2644343c9bcb467ca67f069ff895fcbe"

An unknow error happened in Vagrant OpenStack provider

/opt/vagrant/embedded/gems/gems/rest-client-1.6.8/lib/restclient/request.rb:218:in `rescue in transmit': Request Timeout (RestClient::RequestTimeout)
        from /opt/vagrant/embedded/gems/gems/rest-client-1.6.8/lib/restclient/request.rb:158:in `transmit'
        from /opt/vagrant/embedded/gems/gems/rest-client-1.6.8/lib/restclient/request.rb:68:in `execute'
        from /opt/vagrant/embedded/gems/gems/rest-client-1.6.8/lib/restclient/request.rb:35:in `execute'
        from /home/daveh/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/client/rest_utils.rb:8:in `get'
        from /home/daveh/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/client/http_utils.rb:22:in `block in get'
        from /home/daveh/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/client/http_utils.rb:104:in `authenticated'
        from /home/daveh/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/client/http_utils.rb:21:in `get'
        from /home/daveh/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/client/nova.rb:20:in `get_all_flavors'
        from /home/daveh/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/command/flavor_list.rb:13:in `cmd'
        from /home/daveh/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/command/abstract_command.rb:21:in `execute'
        from /home/daveh/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/command/main.rb:39:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
        from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
```

However, if I execute a wget using the same URL and Auth header, I get the correct response.

```
$ wget --header "X-Auth-Token: 2644343c9bcb467ca67f069ff895fcbe" http://compute-region-domain:8774/v2/a4fa95277a4f4d25b2d8f0e2b3eb6244/flavors/detail
```

I compared the URLs with the URLs listed on the OpenStack Endpoints page and they match.

I get the same issue on both Windows (cygwin) and Linux (RHEL).  I tried increasing the timeouts but they still failed in the end.  If I try to run a `vagrant up --provider=openstack`, I also get the same error - it blocks on the flavor listing.

The vagrant config is

```
config.vm.box       = 'openstack'
config.ssh.username = 'stack'

config.vm.provider :openstack do |os|
	os.openstack_auth_url = 'http://identity-domain:5000/v2.0/tokens'
	os.username           = '****'
	os.password           = '****'
	os.tenant_name        = '****'
	os.region             = 'region'
	os.flavor             = 'micro'
	os.image              = 'OL-6.3.2-latest'
	os.server_name        = 'Test Server'
end
```

I know the config isn't complete, but it should be enough to get past this issue.

Any ideas?  Or anything further I can investigate?

**Comment by f2brossi** [comment]
Have you tried with an open_timeout set to -1  ?  http://stackoverflow.com/questions/4435538/ruby-rest-client-make-it-never-timeout

**Comment by dhallam** [comment]
Thanks for the reply.  I had tried `os.http.open_timeout = 10000` but it didn't appear to have any effect.  I tried `-1` and it's the same - just a 60s timeout.  

All the other responses come back in less than 2 seconds.  And with this particular link, wget comes back in less than 2 seconds as well.

Config is now

```
config.vm.box       = 'openstack'
config.ssh.username = 'stack'

config.vm.provider :openstack do |os|
	os.openstack_auth_url = 'http://identity-domain:5000/v2.0/tokens'
	os.username           = '****'
	os.password           = '****'
	os.tenant_name        = '****'
	os.region             = 'region'
	os.flavor             = 'micro'
	os.image              = 'OL-6.3.2-latest'
	os.server_name        = 'Test Server'
	os.http.open_timeout  = 10000
end
```

Still not working.

**Comment by f2brossi** [comment]
What is strange in your log is having a 300 redirect only to http://image-region-domain:9292.

2015-02-24 19:00 | DEBUG | response => body    : {"versions": [{"status": "CURRENT", "id": "v2.0", "links": [{"href": "http://network-region-domain:9696/v2.0", "rel": "self"}]}]}
RestClient.get "http://image-region-domain:9292", "Accept"=>"application/json", "Accept-Encoding"=>"gzip, deflate", "X-Auth-Token"=>"2644343c9bcb467ca67f069ff895fcbe"
# => 300 MultipleChoices | application/json 715 bytes
2015-02-24 19:00 | DEBUG | response => code    : 300

**Comment by dhallam** [comment]
Thanks again.  Okay - sorted.  For some reason, and I don't know why it was selective about which connections to proxy as they are all internal, but setting `export HTTP_PROXY=` and re-running works.

Closing issue.

**Comment by ggiamarchi** [comment]
@f2brossi 300 is not a redirect, it means "multiple choices". This request is part of the normal process while reading the service catalog. First, we read services base URLs from keystone and then for each service (actually not for all, but most) we call those URLs to list available versions. This call response is a 300 multiple choices with the list of available versions of this service. Then we choose a version which gives us the right URL to use.
