### ISSUE TITLE
Exception while destroying a VM. Instance deleted in openstack but not in .vagrant dir

### ISSUE THREAD

**Issue by theratboss** [ggiamarchi/vagrant-openstack-provider#226]
Exception while destroying a VM. Instance gets deleted in openstack but no in .vagrant dir and after it's deleted and this is indicated by the debug messages it still searches for the ID in the API and fails with {id not found}, which is what should it expect.

Only way of using the machine config again is by manually deleting the files that hold the ID
 rm -rf .vagrant/machines/testvm2

Vagrant 1.4.0
Openstack provider VERSION = '0.6.1'

rat@rat:~/vagrant-openstack$ vagrant destroy testvm2
2015-04-12 18:58 |  INFO | Authenticating on Keystone
2015-04-12 18:58 |  INFO | Authentication on project <tenant-name-hidden> with user <tenant-name-hidden>
2015-04-12 18:58 | DEBUG | request  => method  : POST
2015-04-12 18:58 | DEBUG | request  => url     : http://XXX.XXX.XXX.XXX:5000/v2.0/tokens
2015-04-12 18:58 | DEBUG | request  => headers : {"auth":{"tenantName":"<tenant-name-hidden>","passwordCredentials":{"username":"<tenant-name-hidden>","password":"****"}}}
2015-04-12 18:58 | DEBUG | response => code    : 200
2015-04-12 18:58 | DEBUG | response => headers : {:date=>"Sun, 12 Apr 2015 15:58:14 GMT", :server=>"Apache/2.4.7 (Ubuntu)", :vary=>"X-Auth-Token", :x_openstack_request_id=>"req-b805c4a6-3ae4-43f8-a819-6e33347d83ed", :content_length=>"4541", :content_type=>"application/json"}
2015-04-12 18:58 | DEBUG | response => body    : {"access": {"token": {"issued_at": "2015-04-12T15:58:14.848341", "expires": "2015-04-12T16:58:14Z", "id": "154f76a39full-token-hidden0e0", "tenant": {"description": null, "enabled": true, "id": "050b7a9c21414dd4bff579c787150eb4", "name": "<tenant-name-hidden>"}, "audit_ids": ["2nedeXT2TBag_ivgJAIbhw"]}, "serviceCatalog": [{"endpoints": [{"adminURL": "http://XXX.XXX.XXX.XXX:8774/v2.1/050b7a9c21414dd4bff579c787150eb4", "region": "RegionOne", "internalURL": "http://XXX.XXX.XXX.XXX:8774/v2.1/050b7a9c21414dd4bff579c787150eb4", "id": "117158884f7e4396a1e615080c0c4b23", "publicURL": "http://XXX.XXX.XXX.XXX:8774/v2.1/050b7a9c21414dd4bff579c787150eb4"}], "endpoints_links": [], "type": "computev21", "name": "novav21"}, {"endpoints": [{"adminURL": "http://XXX.XXX.XXX.XXX:8774/v2/050b7a9c21414dd4bff579c787150eb4", "region": "RegionOne", "internalURL": "http://XXX.XXX.XXX.XXX:8774/v2/050b7a9c21414dd4bff579c787150eb4", "id": "68b84d93656948e5a7a20d1fa7b0d627", "publicURL": "http://XXX.XXX.XXX.XXX:8774/v2/050b7a9c21414dd4bff579c787150eb4"}], "endpoints_links": [], "type": "compute", "name": "nova"}, {"endpoints": [{"adminURL": "http://XXX.XXX.XXX.XXX:9696/", "region": "RegionOne", "internalURL": "http://XXX.XXX.XXX.XXX:9696/", "id": "139cb45d2b5143e9bc9cde9793e21a10", "publicURL": "http://XXX.XXX.XXX.XXX:9696/"}], "endpoints_links": [], "type": "network", "name": "neutron"}, {"endpoints": [{"adminURL": "http://XXX.XXX.XXX.XXX:8776/v2/050b7a9c21414dd4bff579c787150eb4", "region": "RegionOne", "internalURL": "http://XXX.XXX.XXX.XXX:8776/v2/050b7a9c21414dd4bff579c787150eb4", "id": "0057c9d387e249d0832ac9806c9eb467", "publicURL": "http://XXX.XXX.XXX.XXX:8776/v2/050b7a9c21414dd4bff579c787150eb4"}], "endpoints_links": [], "type": "volumev2", "name": "cinderv2"}, {"endpoints": [{"adminURL": "http://XXX.XXX.XXX.XXX:3333", "region": "RegionOne", "internalURL": "http://XXX.XXX.XXX.XXX:3333", "id": "1492ae18692149f1be41daa90bc6ea9f", "publicURL": "http://XXX.XXX.XXX.XXX:3333"}], "endpoints_links": [], "type": "s3", "name": "s3"}, {"endpoints": [{"adminURL": "http://XXX.XXX.XXX.XXX:9292", "region": "RegionOne", "internalURL": "http://XXX.XXX.XXX.XXX:9292", "id": "4dab178bec754f6ea3f255bf2221d367", "publicURL": "http://XXX.XXX.XXX.XXX:9292"}], "endpoints_links": [], "type": "image", "name": "glance"}, {"endpoints": [{"adminURL": "http://XXX.XXX.XXX.XXX:8000/v1", "region": "RegionOne", "internalURL": "http://XXX.XXX.XXX.XXX:8000/v1", "id": "378b783cc111446da70bdd7a5dc21422", "publicURL": "http://XXX.XXX.XXX.XXX:8000/v1"}], "endpoints_links": [], "type": "cloudformation", "name": "heat-cfn"}, {"endpoints": [{"adminURL": "http://XXX.XXX.XXX.XXX:8776/v1/050b7a9c21414dd4bff579c787150eb4", "region": "RegionOne", "internalURL": "http://XXX.XXX.XXX.XXX:8776/v1/050b7a9c21414dd4bff579c787150eb4", "id": "62a850dacc74485cbce7a68e31902329", "publicURL": "http://XXX.XXX.XXX.XXX:8776/v1/050b7a9c21414dd4bff579c787150eb4"}], "endpoints_links": [], "type": "volume", "name": "cinder"}, {"endpoints": [{"adminURL": "http://XXX.XXX.XXX.XXX:8773/", "region": "RegionOne", "internalURL": "http://XXX.XXX.XXX.XXX:8773/", "id": "36f79b8c72e14526828993ab6c8f135f", "publicURL": "http://XXX.XXX.XXX.XXX:8773/"}], "endpoints_links": [], "type": "ec2", "name": "ec2"}, {"endpoints": [{"adminURL": "http://XXX.XXX.XXX.XXX:8004/v1/050b7a9c21414dd4bff579c787150eb4", "region": "RegionOne", "internalURL": "http://XXX.XXX.XXX.XXX:8004/v1/050b7a9c21414dd4bff579c787150eb4", "id": "3e46cf5673c142948bb78598dd47f7c7", "publicURL": "http://XXX.XXX.XXX.XXX:8004/v1/050b7a9c21414dd4bff579c787150eb4"}], "endpoints_links": [], "type": "orchestration", "name": "heat"}, {"endpoints": [{"adminURL": "http://XXX.XXX.XXX.XXX:8080", "region": "RegionOne", "internalURL": "http://XXX.XXX.XXX.XXX:8080/v1/AUTH_050b7a9c21414dd4bff579c787150eb4", "id": "7f395a6dbe114b8994a7b4d3e35d4040", "publicURL": "http://XXX.XXX.XXX.XXX:8080/v1/AUTH_050b7a9c21414dd4bff579c787150eb4"}], "endpoints_links": [], "type": "object-store", "name": "swift"}, {"endpoints": [{"adminURL": "http://XXX.XXX.XXX.XXX:35357/v2.0", "region": "RegionOne", "internalURL": "http://XXX.XXX.XXX.XXX:5000/v2.0", "id": "256ceabf439e476ebbacbb5d1d0fbc1e", "publicURL": "http://XXX.XXX.XXX.XXX:5000/v2.0"}], "endpoints_links": [], "type": "identity", "name": "keystone"}], "user": {"username": "<tenant-name-hidden>", "roles_links": [], "id": "bc6ab83145b84c67b987985bd3c8e059", "roles": [{"name": "anotherrole"}, {"name": "Member"}], "name": "<tenant-name-hidden>"}, "metadata": {"is_admin": 0, "roles": ["03dc78149c9e482a82d45b45df951ec6", "80f9905508f14edcb0e99ea8228cef90"]}}}
2015-04-12 18:58 |  INFO | Looking for available endpoints...
2015-04-12 18:58 | DEBUG | request  => method  : GET
2015-04-12 18:58 | DEBUG | request  => url     : http://XXX.XXX.XXX.XXX:9696/
2015-04-12 18:58 | DEBUG | request  => headers : {"X-Auth-Token"=>"154f76a39full-token-hidden0e0", :accept=>:json}
2015-04-12 18:58 | DEBUG | response => code    : 200
2015-04-12 18:58 | DEBUG | response => headers : {:content_type=>"application/json; charset=UTF-8", :content_length=>"122", :date=>"Sun, 12 Apr 2015 15:58:14 GMT"}
2015-04-12 18:58 | DEBUG | response => body    : {"versions": [{"status": "CURRENT", "id": "v2.0", "links": [{"href": "http://XXX.XXX.XXX.XXX:9696/v2.0", "rel": "self"}]}]}
2015-04-12 18:58 | DEBUG | response => code    : 300
2015-04-12 18:58 | DEBUG | response => headers : {:content_type=>"application/json; charset=UTF-8", :content_length=>"664", :date=>"Sun, 12 Apr 2015 15:58:14 GMT"}
2015-04-12 18:58 | DEBUG | response => body    : {"versions": [{"status": "CURRENT", "id": "v2.3", "links": [{"href": "http://XXX.XXX.XXX.XXX:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.2", "links": [{"href": "http://XXX.XXX.XXX.XXX:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.1", "links": [{"href": "http://XXX.XXX.XXX.XXX:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.0", "links": [{"href": "http://XXX.XXX.XXX.XXX:9292/v2/", "rel": "self"}]}, {"status": "CURRENT", "id": "v1.1", "links": [{"href": "http://XXX.XXX.XXX.XXX:9292/v1/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v1.0", "links": [{"href": "http://XXX.XXX.XXX.XXX:9292/v1/", "rel": "self"}]}]}
2015-04-12 18:58 |  INFO |  -- computev21     : http://XXX.XXX.XXX.XXX:8774/v2.1/050b7a9c21414dd4bff579c787150eb4
2015-04-12 18:58 |  INFO |  -- compute        : http://XXX.XXX.XXX.XXX:8774/v2/050b7a9c21414dd4bff579c787150eb4
2015-04-12 18:58 |  INFO |  -- network        : http://XXX.XXX.XXX.XXX:9696/v2.0
2015-04-12 18:58 |  INFO |  -- volumev2       : http://XXX.XXX.XXX.XXX:8776/v2/050b7a9c21414dd4bff579c787150eb4
2015-04-12 18:58 |  INFO |  -- s3             : http://XXX.XXX.XXX.XXX:3333
2015-04-12 18:58 |  INFO |  -- image          : http://XXX.XXX.XXX.XXX:9292/v2/
2015-04-12 18:58 |  INFO |  -- cloudformation : http://XXX.XXX.XXX.XXX:8000/v1
2015-04-12 18:58 |  INFO |  -- volume         : http://XXX.XXX.XXX.XXX:8776/v1/050b7a9c21414dd4bff579c787150eb4
2015-04-12 18:58 |  INFO |  -- ec2            : http://XXX.XXX.XXX.XXX:8773/
2015-04-12 18:58 |  INFO |  -- orchestration  : http://XXX.XXX.XXX.XXX:8004/v1/050b7a9c21414dd4bff579c787150eb4
2015-04-12 18:58 |  INFO |  -- object-store   : http://XXX.XXX.XXX.XXX:8080/v1/AUTH_050b7a9c21414dd4bff579c787150eb4
2015-04-12 18:58 |  INFO |  -- identity       : http://XXX.XXX.XXX.XXX:5000/v2.0
2015-04-12 18:58 | DEBUG | block in get_server_details - start
2015-04-12 18:58 | DEBUG | request  => method  : GET
2015-04-12 18:58 | DEBUG | request  => url     : http://XXX.XXX.XXX.XXX:8774/v2/050b7a9c21414dd4bff579c787150eb4/servers/d7df1c11-ee89-4579-a41c-9426c1b62084
2015-04-12 18:58 | DEBUG | request  => headers : {"X-Auth-Token"=>"154f76a39full-token-hidden0e0", :accept=>:json}
2015-04-12 18:58 | DEBUG | response => code    : 200
2015-04-12 18:58 | DEBUG | response => headers : {:content_type=>"application/json", :content_length=>"1688", :x_compute_request_id=>"req-79c6eb4f-b1b4-4578-a0eb-a2a895f4f55d", :date=>"Sun, 12 Apr 2015 15:58:15 GMT"}
2015-04-12 18:58 | DEBUG | response => body    : {"server": {"status": "ACTIVE", "updated": "2015-04-12T15:42:55Z", "hostId": "520ec34230617d262815f20c7fd3c3f08d82ad2943393d3cda0e4e06", "addresses": {"private": [{"OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:48:bb:4b", "version": 4, "addr": "10.0.0.28", "OS-EXT-IPS:type": "fixed"}, {"OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:48:bb:4b", "version": 4, "addr": "172.24.4.13", "OS-EXT-IPS:type": "floating"}]}, "links": [{"href": "http://XXX.XXX.XXX.XXX:8774/v2/050b7a9c21414dd4bff579c787150eb4/servers/d7df1c11-ee89-4579-a41c-9426c1b62084", "rel": "self"}, {"href": "http://XXX.XXX.XXX.XXX:8774/050b7a9c21414dd4bff579c787150eb4/servers/d7df1c11-ee89-4579-a41c-9426c1b62084", "rel": "bookmark"}], "key_name": "vagrant-generated-mdykv6sq", "image": {"id": "117b0530-b6a6-4c9c-9a52-590666c825dd", "links": [{"href": "http://XXX.XXX.XXX.XXX:8774/050b7a9c21414dd4bff579c787150eb4/images/117b0530-b6a6-4c9c-9a52-590666c825dd", "rel": "bookmark"}]}, "OS-EXT-STS:task_state": null, "OS-EXT-STS:vm_state": "active", "OS-SRV-USG:launched_at": "2015-04-12T15:42:55.000000", "flavor": {"id": "2", "links": [{"href": "http://XXX.XXX.XXX.XXX:8774/050b7a9c21414dd4bff579c787150eb4/flavors/2", "rel": "bookmark"}]}, "id": "d7df1c11-ee89-4579-a41c-9426c1b62084", "security_groups": [{"name": "default"}], "OS-SRV-USG:terminated_at": null, "OS-EXT-AZ:availability_zone": "nova", "user_id": "bc6ab83145b84c67b987985bd3c8e059", "name": "testvm2", "created": "2015-04-12T15:42:49Z", "tenant_id": "050b7a9c21414dd4bff579c787150eb4", "OS-DCF:diskConfig": "MANUAL", "os-extended-volumes:volumes_attached": [], "accessIPv4": "", "accessIPv6": "", "progress": 0, "OS-EXT-STS:power_state": 1, "config_drive": "True", "metadata": {}}}
2015-04-12 18:58 | DEBUG | block in get_server_details - end
2015-04-12 18:58 |  INFO | Deleting server d7df1c11-ee89-4579-a41c-9426c1b62084...
[testvm2] Deleting server...
2015-04-12 18:58 | DEBUG | block in delete_server - start
2015-04-12 18:58 | DEBUG | request  => method  : DELETE
2015-04-12 18:58 | DEBUG | request  => url     : http://XXX.XXX.XXX.XXX:8774/v2/050b7a9c21414dd4bff579c787150eb4/servers/d7df1c11-ee89-4579-a41c-9426c1b62084
2015-04-12 18:58 | DEBUG | request  => headers : {"X-Auth-Token"=>"154f76a39full-token-hidden0e0", :accept=>:json, :content_type=>:json}
2015-04-12 18:58 | DEBUG | response => code    : 204
2015-04-12 18:58 | DEBUG | response => headers : {:content_length=>"0", :content_type=>"application/json", :x_compute_request_id=>"req-20fb7121-0ef5-4521-b61a-9dfb43226949", :date=>"Sun, 12 Apr 2015 15:58:15 GMT"}
2015-04-12 18:58 | DEBUG | response => body    :
2015-04-12 18:58 | DEBUG | block in delete_server - end
2015-04-12 18:58 | DEBUG | block in get_server_details - start
2015-04-12 18:58 | DEBUG | request  => method  : GET
2015-04-12 18:58 | DEBUG | request  => url     : http://XXX.XXX.XXX.XXX:8774/v2/050b7a9c21414dd4bff579c787150eb4/servers/d7df1c11-ee89-4579-a41c-9426c1b62084
2015-04-12 18:58 | DEBUG | request  => headers : {"X-Auth-Token"=>"154f76a39full-token-hidden0e0", :accept=>:json}
2015-04-12 18:58 | DEBUG | response => code    : 200
2015-04-12 18:58 | DEBUG | response => headers : {:content_type=>"application/json", :content_length=>"1694", :x_compute_request_id=>"req-881f472c-3712-4532-9365-e927757e6761", :date=>"Sun, 12 Apr 2015 15:58:15 GMT"}
2015-04-12 18:58 | DEBUG | response => body    : {"server": {"status": "ACTIVE", "updated": "2015-04-12T15:58:15Z", "hostId": "520ec34230617d262815f20c7fd3c3f08d82ad2943393d3cda0e4e06", "addresses": {"private": [{"OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:48:bb:4b", "version": 4, "addr": "10.0.0.28", "OS-EXT-IPS:type": "fixed"}, {"OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:48:bb:4b", "version": 4, "addr": "172.24.4.13", "OS-EXT-IPS:type": "floating"}]}, "links": [{"href": "http://XXX.XXX.XXX.XXX:8774/v2/050b7a9c21414dd4bff579c787150eb4/servers/d7df1c11-ee89-4579-a41c-9426c1b62084", "rel": "self"}, {"href": "http://XXX.XXX.XXX.XXX:8774/050b7a9c21414dd4bff579c787150eb4/servers/d7df1c11-ee89-4579-a41c-9426c1b62084", "rel": "bookmark"}], "key_name": "vagrant-generated-mdykv6sq", "image": {"id": "117b0530-b6a6-4c9c-9a52-590666c825dd", "links": [{"href": "http://XXX.XXX.XXX.XXX:8774/050b7a9c21414dd4bff579c787150eb4/images/117b0530-b6a6-4c9c-9a52-590666c825dd", "rel": "bookmark"}]}, "OS-EXT-STS:task_state": "deleting", "OS-EXT-STS:vm_state": "active", "OS-SRV-USG:launched_at": "2015-04-12T15:42:55.000000", "flavor": {"id": "2", "links": [{"href": "http://XXX.XXX.XXX.XXX:8774/050b7a9c21414dd4bff579c787150eb4/flavors/2", "rel": "bookmark"}]}, "id": "d7df1c11-ee89-4579-a41c-9426c1b62084", "security_groups": [{"name": "default"}], "OS-SRV-USG:terminated_at": null, "OS-EXT-AZ:availability_zone": "nova", "user_id": "bc6ab83145b84c67b987985bd3c8e059", "name": "testvm2", "created": "2015-04-12T15:42:49Z", "tenant_id": "050b7a9c21414dd4bff579c787150eb4", "OS-DCF:diskConfig": "MANUAL", "os-extended-volumes:volumes_attached": [], "accessIPv4": "", "accessIPv6": "", "progress": 0, "OS-EXT-STS:power_state": 1, "config_drive": "True", "metadata": {}}}
2015-04-12 18:58 | DEBUG | block in get_server_details - end
2015-04-12 18:58 | DEBUG | block in delete_keypair_if_vagrant - start
2015-04-12 18:58 | DEBUG | request  => method  : DELETE
2015-04-12 18:58 | DEBUG | request  => url     : http://XXX.XXX.XXX.XXX:8774/v2/050b7a9c21414dd4bff579c787150eb4/os-keypairs/vagrant-generated-mdykv6sq
2015-04-12 18:58 | DEBUG | request  => headers : {"X-Auth-Token"=>"154f76a39full-token-hidden0e0", :accept=>:json, :content_type=>:json}
2015-04-12 18:58 | DEBUG | response => code    : 202
2015-04-12 18:58 | DEBUG | response => headers : {:content_type=>"text/html; charset=UTF-8", :content_length=>"0", :x_compute_request_id=>"req-e06f85d0-b402-465b-898e-728337d00079", :date=>"Sun, 12 Apr 2015 15:58:15 GMT"}
2015-04-12 18:58 | DEBUG | response => body    :
2015-04-12 18:58 | DEBUG | block in delete_keypair_if_vagrant - end
2015-04-12 18:58 |  INFO | Waiting for the instance with id d7df1c11-ee89-4579-a41c-9426c1b62084 to be deleted...
[testvm2] Waiting for the server to be deleted...
2015-04-12 18:58 | DEBUG | Waiting for instance to be DELETED
2015-04-12 18:58 | DEBUG | block in get_server_details - start
2015-04-12 18:58 | DEBUG | request  => method  : GET
2015-04-12 18:58 | DEBUG | request  => url     : http://XXX.XXX.XXX.XXX:8774/v2/050b7a9c21414dd4bff579c787150eb4/servers/d7df1c11-ee89-4579-a41c-9426c1b62084
2015-04-12 18:58 | DEBUG | request  => headers : {"X-Auth-Token"=>"154f76a39full-token-hidden0e0", :accept=>:json}
2015-04-12 18:58 | DEBUG | response => code    : 200
2015-04-12 18:58 | DEBUG | response => headers : {:content_type=>"application/json", :content_length=>"1694", :x_compute_request_id=>"req-88f2b682-d7bd-438b-b7ce-a20390f9dfae", :date=>"Sun, 12 Apr 2015 15:58:15 GMT"}
2015-04-12 18:58 | DEBUG | response => body    : {"server": {"status": "ACTIVE", "updated": "2015-04-12T15:58:15Z", "hostId": "520ec34230617d262815f20c7fd3c3f08d82ad2943393d3cda0e4e06", "addresses": {"private": [{"OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:48:bb:4b", "version": 4, "addr": "10.0.0.28", "OS-EXT-IPS:type": "fixed"}, {"OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:48:bb:4b", "version": 4, "addr": "172.24.4.13", "OS-EXT-IPS:type": "floating"}]}, "links": [{"href": "http://XXX.XXX.XXX.XXX:8774/v2/050b7a9c21414dd4bff579c787150eb4/servers/d7df1c11-ee89-4579-a41c-9426c1b62084", "rel": "self"}, {"href": "http://XXX.XXX.XXX.XXX:8774/050b7a9c21414dd4bff579c787150eb4/servers/d7df1c11-ee89-4579-a41c-9426c1b62084", "rel": "bookmark"}], "key_name": "vagrant-generated-mdykv6sq", "image": {"id": "117b0530-b6a6-4c9c-9a52-590666c825dd", "links": [{"href": "http://XXX.XXX.XXX.XXX:8774/050b7a9c21414dd4bff579c787150eb4/images/117b0530-b6a6-4c9c-9a52-590666c825dd", "rel": "bookmark"}]}, "OS-EXT-STS:task_state": "deleting", "OS-EXT-STS:vm_state": "active", "OS-SRV-USG:launched_at": "2015-04-12T15:42:55.000000", "flavor": {"id": "2", "links": [{"href": "http://XXX.XXX.XXX.XXX:8774/050b7a9c21414dd4bff579c787150eb4/flavors/2", "rel": "bookmark"}]}, "id": "d7df1c11-ee89-4579-a41c-9426c1b62084", "security_groups": [{"name": "default"}], "OS-SRV-USG:terminated_at": null, "OS-EXT-AZ:availability_zone": "nova", "user_id": "bc6ab83145b84c67b987985bd3c8e059", "name": "testvm2", "created": "2015-04-12T15:42:49Z", "tenant_id": "050b7a9c21414dd4bff579c787150eb4", "OS-DCF:diskConfig": "MANUAL", "os-extended-volumes:volumes_attached": [], "accessIPv4": "", "accessIPv6": "", "progress": 0, "OS-EXT-STS:power_state": 1, "config_drive": "True", "metadata": {}}}
2015-04-12 18:58 | DEBUG | block in get_server_details - end
2015-04-12 18:58 | DEBUG | Waiting for instance to be DELETED
2015-04-12 18:58 | DEBUG | block in get_server_details - start
2015-04-12 18:58 | DEBUG | request  => method  : GET
2015-04-12 18:58 | DEBUG | request  => url     : http://XXX.XXX.XXX.XXX:8774/v2/050b7a9c21414dd4bff579c787150eb4/servers/d7df1c11-ee89-4579-a41c-9426c1b62084
2015-04-12 18:58 | DEBUG | request  => headers : {"X-Auth-Token"=>"154f76a39full-token-hidden0e0", :accept=>:json}
2015-04-12 18:58 | DEBUG | response => code    : 404
2015-04-12 18:58 | DEBUG | response => headers : {:content_length=>"111", :content_type=>"application/json; charset=UTF-8", :x_compute_request_id=>"req-1c204d9e-1797-4875-8a17-bfff1d5d856a", :date=>"Sun, 12 Apr 2015 15:58:18 GMT"}
2015-04-12 18:58 | DEBUG | response => body    : {"itemNotFound": {"message": "Instance d7df1c11-ee89-4579-a41c-9426c1b62084 could not be found.", "code": 404}}
An unknow error happened in Vagrant OpenStack provider

To easily debug what happened, we recommend to set the environment
variable VAGRANT_OPENSTACK_LOG to debug

```
$ export VAGRANT_OPENSTACK_LOG=debug
```

If doing this does not help fixing your issue, there may be a bug
in the provider. Please submit an issue on Github at
https://github.com/ggiamarchi/vagrant-openstack-provider
with the stracktrace and the logs.

We are looking for feedback, so feel free to ask questions or
describe features you would like to see in this provider.
/home/rat/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/client/nova.rb:180:in `rescue in instance_exists': Catched Error: Catched Error: undefined method`extra_data' for #VagrantPlugins::Openstack::Errors::VagrantOpenstackError:0x000000026e71f0 (NoMethodError)
        from /home/rat/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/client/nova.rb:178:in `instance_exists'
        from /home/rat/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/client/nova.rb:103:in`get_server_details'
        from /home/rat/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/action/delete_server.rb:40:in `block in waiting_for_instance_to_be_deleted'
        from /opt/vagrant/embedded/lib/ruby/2.0.0/timeout.rb:66:in`timeout'
        from /opt/vagrant/embedded/lib/ruby/2.0.0/timeout.rb:97:in `timeout'
        from /home/rat/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/action/delete_server.rb:35:in`waiting_for_instance_to_be_deleted'
        from /home/rat/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/action/delete_server.rb:22:in `execute'
        from /home/rat/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/action/abstract_action.rb:8:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:95:in`block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/runner.rb:69:in`block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/runner.rb:69:in`run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/call.rb:51:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in`call'
        from /home/rat/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/action/connect_openstack.rb:32:in `execute'
        from /home/rat/.vagrant.d/gems/gems/vagrant-openstack-provider-0.6.1/lib/vagrant-openstack-provider/action/abstract_action.rb:8:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/config_validate.rb:25:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
        from /home/rat/.vagrant.d/gems/gems/vagrant-hostmanager-1.5.0/lib/vagrant-hostmanager/action/update_all.rb:30:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/config_validate.rb:25:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builder.rb:116:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/runner.rb:69:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/util/busy.rb:19:in`busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/runner.rb:69:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/machine.rb:147:in`action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/commands/destroy/command.rb:28:in `block in execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/plugin/v2/command.rb:193:in`block in with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/plugin/v2/command.rb:191:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/plugin/v2/command.rb:191:in`with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/commands/destroy/command.rb:27:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/cli.rb:38:in`execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/environment.rb:484:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.4.0/bin/vagrant:127:in`<top (required)>'
        from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
        from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in`<main>'

**Comment by ggiamarchi** [comment]
Closing for long inactivity
