### ISSUE TITLE
Error: Operation already in progress

### ISSUE THREAD

**Issue by dearchap** [ggiamarchi/vagrant-openstack-provider#373]
An unknown error happened in Vagrant OpenStack provider
To easily debug what happened, we recommend to set the environment
variable VAGRANT_OPENSTACK_LOG to debug
    $ export VAGRANT_OPENSTACK_LOG=debug
If doing this does not help fixing your issue, there may be a bug
in the provider. Please submit an issue on Github at
https://github.com/ggiamarchi/vagrant-openstack-provider
with the stracktrace and the logs.
We are looking for feedback, so feel free to ask questions or
describe features you would like to see in this provider.
/opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:1198:in `__connect_nonblock': Catched Error: Catched Error: Catched Error: Operation already in progress - connect(2) for 10.62.178.136:22 (Errno::EALREADY)
        from /opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:1198:in `connect_nonblock'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:56:in `connect_internal'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:137:in `connect'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:627:in `block in tcp'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:227:in `each'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:227:in `foreach'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:617:in `tcp'
        from /opt/vagrant/embedded/gems/2.1.4/gems/net-ssh-5.0.2/lib/net/ssh/transport/session.rb:73:in `initialize'
        from /opt/vagrant/embedded/gems/2.1.4/gems/net-ssh-5.0.2/lib/net/ssh.rb:242:in `new'
        from /opt/vagrant/embedded/gems/2.1.4/gems/net-ssh-5.0.2/lib/net/ssh.rb:242:in `start'
        from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/plugins/communicators/ssh/communicator.rb:415:in `block (2 levels) in connect'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
        from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/plugins/communicators/ssh/communicator.rb:389:in `block in connect'
        from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/util/retryable.rb:17:in `retryable'
        from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/plugins/communicators/ssh/communicator.rb:388:in `connect'
        from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/plugins/communicators/ssh/communicator.rb:84:in `block in wait_for_ready'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
        from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/plugins/communicators/ssh/communicator.rb:62:in `wait_for_ready'
        from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'

**Comment by venushka** [comment]
I am getting the same when running on Windows 10 WSL :(

**OS:** Windows 10 Pro (Version 1803)
**Vagrant version:** 2.2.2 (64-bit)

**WSL:** Ubuntu 18.04 (Version 1804.2018.817.0)
**Vagrant version:** 2.2.2 (for Debian)
**vagrant-openstack-provider version:** 0.13.0

This is the full trace. Tried with debug as suggested, but the result it the same apart from the printing all REST API calls before this.

```
    ubuntu: SSH address: 192.168.1.10:22
    ubuntu: SSH username: ubuntu
    ubuntu: SSH auth method: private key
An unknown error happened in Vagrant OpenStack provider

To easily debug what happened, we recommend to set the environment
variable VAGRANT_OPENSTACK_LOG to debug

    $ export VAGRANT_OPENSTACK_LOG=debug

If doing this does not help fixing your issue, there may be a bug
in the provider. Please submit an issue on Github at
https://github.com/ggiamarchi/vagrant-openstack-provider
with the stracktrace and the logs.

We are looking for feedback, so feel free to ask questions or
describe features you would like to see in this provider.
/opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:1198:in `__connect_nonblock': Catched Error: Catched Error: Catched Error: Operation already in progress - connect(2) for 192.168.1.10:22 (Errno::EALREADY)
        from /opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:1198:in `connect_nonblock'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:56:in `connect_internal'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:137:in `connect'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:627:in `block in tcp'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:227:in `each'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:227:in `foreach'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/socket.rb:617:in `tcp'
        from /opt/vagrant/embedded/gems/2.2.2/gems/net-ssh-5.0.2/lib/net/ssh/transport/session.rb:73:in `initialize'
        from /opt/vagrant/embedded/gems/2.2.2/gems/net-ssh-5.0.2/lib/net/ssh.rb:242:in `new'
        from /opt/vagrant/embedded/gems/2.2.2/gems/net-ssh-5.0.2/lib/net/ssh.rb:242:in `start'
        from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/communicators/ssh/communicator.rb:425:in `block (2 levels) in connect'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
        from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/communicators/ssh/communicator.rb:399:in `block in connect'
        from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/util/retryable.rb:17:in `retryable'
        from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/communicators/ssh/communicator.rb:398:in `connect'
        from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/communicators/ssh/communicator.rb:86:in `block in wait_for_ready'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
        from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/communicators/ssh/communicator.rb:62:in `wait_for_ready'
        from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
```
Please let me know if I can provider any other information.

**Comment by piotr-ce** [comment]
Seems like the same issue, often when doing vagrant up, but also vagrant halt

Vagrant 2.2.4
Windows 10.0.17763 build
Provider: Hyper-V

Trace
